### PR TITLE
Fix building errors and warnings under Android Studio

### PR DESCRIPTION
**Pull request by dottools**
This pull request fixes the following issues:
* Gradle build failure due to .cmd extension missing for ndk-build of which is required on Windows.
 * Simple fix by appending the extension when Windows is detected as the OS.
* Compiler errors due to several enum names being used as a namespace.
 * I know this is allowed with C++11, but it seems to not be enabled or available with current build-tools releases.
* Minor, but annoying compiler warnings.

### CODE REVIEW

**Comment by yurembo** [comment]
Thanks. I can not wait to try this :+1:

**Comment by greenfire27** [comment]
Thanks dottools!

**Comment by yurembo** [comment]
Oh, great! I have tested this already, and everything works really fine!
Only, I decreased SDK version from 22 to 19:

compileSdkVersion 19
minSdkVersion 19
targetSdkVersion 19

And it works great!

**Comment by dottools** [comment]
I'm glad that it works for you too. :)

I only chose the target SDK version in order to test to make sure it works, runs and debugging, on my amazon fire 7" tablet running Fire 5.1.1 OS (Android 5.1 base). And it does perfectly fine.

I wasn't sure about whether or not to revert the sdk version back to what was already there, but I figured well it is indeed working for me so perhaps I shouldn't change it to something I couldn't test and verify with.

**Pull request merged**
