### PR TITLE
Fix Make build

### PR DESCRIPTION
**Pull request by losinggeneration**
* Looks like at least one thing has gone away (ImageFont.cc) and vorbis
  and ogg were not added to be built with the Make build

### CODE REVIEW

**Comment by greenfire27** [comment]
Thanks for the helping hand!  We don't currently have a unix guy on the steering committee so stuff like this often falls through the cracks.

My most recent pull request https://github.com/GarageGames/Torque2D/pull/326 removed ImageFont and replaced it with the TextSprite.  I think I added about 10 files that will probably need to be included in the make file.  Any chance you could take a look and add those in as well?

**Comment by losinggeneration** [comment]
Yeah, I think I can pull that in too. It looks like there are a couple compiler errors that I'm working through now.

**Comment by losinggeneration** [comment]
Ok @greenfire27 I think it's ready now. You should test it on other platforms to make sure none of the header changes affected things there.

**Comment by greenfire27** [comment]
The header changes look fine.  I'll test them on my system.  I think you're still missing BitmapFontCharacterInfo.h and BitmapFontLineInfo.h.  Once you have it built, confirm that the TextSprite Toy works and then I'm merge.

Thanks again for all your help!

**Comment by losinggeneration** [comment]
Headers aren't included in the Makefile. So, I'm unsure what you mean by me still missing them. In any event, the TextSprite Toy does work.

However, I will note that there are some problems with the Linux build still. For instance, the GUI buttons in the sandbox do not respond to click events and the mouse is not visible (I tried forcing it visible with SDL_ShowCursor.) It looked like ~ should bring up a console, and that didn't work. That said, I didn't fully read the AppCore/Sandbox code and I may just be missing something.

**Comment by greenfire27** [comment]
Excuse me, my Makefile ignorance is showing.

The key combination to bring up the console is control + ~ so that might be the answer to that problem.  The other stuff worries me though.  Linux needs more love.  Which type of Linux are you on?

**Comment by losinggeneration** [comment]
You can specify headers in the makefiles for dependency resolution so when headers changed, it knows what to rebuild, but, and it's been awhile, but I believe there are ways around having to specify the headers explicitly. 

Ctrl+~ works. What doesn't work is clicking on "Hide Log" I'll try to spend a bit more time and try to track down why mouse events aren't working for the GUI. They trigger events in the main scene (like movement in the truck toy.)
 
As for Linux distribution, I'm using Debian.

**Pull request merged**
