### PR TITLE
Feature/u64

### PR DESCRIPTION
**Pull request by pchan126**
Doing a little housecleaning here. Replacing old typedefs with stl typedefs.

### CODE REVIEW

**Comment by dottools** [comment]
This breaks pre-VS2013 and older GCC compilers :(

**Comment by pchan126** [comment]
I did let these changes sit on my branch for 6 months. :)

**Comment by greenfire27** [comment]
Are there any opinions about merging this now that we don't support anything before VS2013?

**Comment by chaigler** [comment]
I'm not clear on what we gain from this? Is there a need to change the typedefs?

**Comment by greenfire27** [comment]
Although I like the idea of removing support for very old platforms like codewarrior, I worry that changing typedefs might have some unexpected consequences.  Given our inability right now to thoroughly test things I've decided to pass on this pull request and leave things as they are for now.

**Pull request closed without merging**
