### PR TITLE
VS2013 fixes

### PR DESCRIPTION
**Pull request by elementc**
defaulted to wrong working directory for VS2013 
debug.

Used wrong version of leap libs.

Strongly recommend dropping VS2010 and VS2012. Will provide PR if you guys want it.

### CODE REVIEW

**Comment by elementc** [comment]
fixes #212

**Comment by chaigler** [comment]
Thanks @elementc.

Peter and I talked about dropping support for anything below VS2013 during the last committee meeting. If you want to provide a pull request to remove those that'd be great.

**Comment by chaigler** [comment]
@elementc Is this PR against the most updated version of the development branch? It looks like this issue was resolved by mistake when my ogg support stuff was added. I changed the VS2013 project to add libogg/libvorbis and (somehow) also pulled in a change to link against the correct Leap lib as well.

**Comment by elementc** [comment]
i'm a dumb. it is now. This still fixes a warning that pops up when attempting to launch a release build in VS2k13, turned out to be a net one line change.

**Pull request merged**
