### PR TITLE
Releasing for Android required changes

### PR DESCRIPTION
**Pull request by marauder2k7**
-Upgrade LIBPNG due to vulnerability
-added 64bit precompiled libraries for Freetype and OpenAL
-added necessary changes for arm64-v8a

### CODE REVIEW

**Comment by greenfire27** [comment]
Your openAL fix includes a lot of *.o.d files (which I assume are compiled object files or something) that have your hard coded path. I'm going to guess that those aren't actually needed to fix this. At any rate they won't work for everyone else.

**Comment by marauder2k7** [comment]
you would be 100% right lol sorry about that, i was getting a bit excited over finally getting audio to work lol they can be removed

**Comment by marauder2k7** [comment]
there we go useless files removed :D

**Comment by dottools** [comment]
This is going to have to be redone. Because there exists a commit with those files existing then they'll always exist in the repository when the PR merged even though you later removed them in a later commit, cause git tracks everything, therefore if they ever existed it'll continue to exist in storage space. So you'll have to squash your commits.

Also do not commit precompiled anything, cause it will not work for all architectures. The initial PR included a lot of unnecessary files. We only needed the used source files, not the entire libpng release archive.

So overall this entire PR will have to be redone.

**Comment by marauder2k7** [comment]
no problem i can re-do it

**Pull request closed without merging**
