### PR TITLE
Android Studio

### PR DESCRIPTION
**Pull request by yurembo**
Add Android Studio support from elementc

### CODE REVIEW

**Comment by elementc** [comment]
@yurembo have you built this yet? I actually still haven't overcome any of the bugs and problems I listed in the forum thread. Was waiting for AS2 which is supposed to have some NDK fixes.

**Comment by yurembo** [comment]
@elementc 
yes, this works really fine from "the box"!
thanks for your great job!

**Comment by elementc** [comment]
If it's alright, mind if I issue the PR from my repo directly? For my resume.

**Comment by yurembo** [comment]
Of couse, you should make this!

**Comment by elementc** [comment]
Issued as #278, feel free to close. Thanks for the extra testing!

**Comment by yurembo** [comment]
I have noticed only one thing: Windows users would append ".cmd" to the lines $ndkDir/ndk-build in a "build.gradle (Module: app)" file. Otherwise a building process would fall. Because command files on Mac OS X have not an extension but on Windows these have a ".cmd" extension.

**Comment by elementc** [comment]
I'd welcome a PR to fix that, I don't have a windows machine with AS set up at the moment.

**Pull request closed without merging**
